name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.2"

      - name: Build project
        run: |
          # AMD64 builds
          GOOS=linux GOARCH=amd64 go build -o newpro-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o newpro-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o newpro-darwin-amd64

          # ARM64 builds
          GOOS=linux GOARCH=arm64 go build -o newpro-linux-arm64
          GOOS=windows GOARCH=arm64 go build -o newpro-windows-arm64.exe
          GOOS=darwin GOARCH=arm64 go build -o newpro-darwin-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            newpro-linux-amd64
            newpro-windows-amd64.exe
            newpro-darwin-amd64
            newpro-linux-arm64
            newpro-windows-arm64.exe
            newpro-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
